apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-ba5e
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-ba5e
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-ba5e
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-ba5e
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-ba5e
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ghdx-tenant/status-quarkus-io/statusquarkusio-ba5e@sha256:28deb6cc82385990c136ea706ed94b26a07bc02e318abfc90a2d0d12d294cd3d
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
